# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task_service.proto\x12\x0btaskservice\"\x19\n\nCsvRequest\x12\x0b\n\x03row\x18\x01 \x01(\t\"\x1e\n\x0b\x43svResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0c\x45mailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"0\n\x0e\x44omainResponse\x12\x0e\n\x06has_mx\x18\x01 \x01(\x08\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0cWordResponse\x12\x0c\n\x04word\x18\x01 \x01(\t2\xd7\x01\n\x0bTaskService\x12=\n\x08WriteCsv\x12\x17.taskservice.CsvRequest\x1a\x18.taskservice.CsvResponse\x12\x45\n\x0b\x43heckDomain\x12\x19.taskservice.EmailRequest\x1a\x1b.taskservice.DomainResponse\x12\x42\n\x0bLongestWord\x12\x18.taskservice.TextRequest\x1a\x19.taskservice.WordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSVREQUEST']._serialized_start=35
  _globals['_CSVREQUEST']._serialized_end=60
  _globals['_CSVRESPONSE']._serialized_start=62
  _globals['_CSVRESPONSE']._serialized_end=92
  _globals['_EMAILREQUEST']._serialized_start=94
  _globals['_EMAILREQUEST']._serialized_end=123
  _globals['_DOMAINRESPONSE']._serialized_start=125
  _globals['_DOMAINRESPONSE']._serialized_end=173
  _globals['_TEXTREQUEST']._serialized_start=175
  _globals['_TEXTREQUEST']._serialized_end=202
  _globals['_WORDRESPONSE']._serialized_start=204
  _globals['_WORDRESPONSE']._serialized_end=232
  _globals['_TASKSERVICE']._serialized_start=235
  _globals['_TASKSERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
