syntax = "proto3";

package taskservice;

service TaskService {
    rpc WriteCsv (CsvRequest) returns (CsvResponse);
    rpc CheckDomain (EmailRequest) returns (DomainResponse);
    rpc LongestWord (TextRequest) returns (WordResponse);
}

message CsvRequest {
    string row = 1;
}

message CsvResponse {
    string message = 1;
}

message EmailRequest {
    string email = 1;
}

message DomainResponse {
    bool has_mx = 1;
    string domain = 2;
}

message TextRequest {
    string text = 1;
}

message WordResponse {
    string word = 1;
}