# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import task_service_pb2 as task__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in task_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteCsv = channel.unary_unary(
                '/taskservice.TaskService/WriteCsv',
                request_serializer=task__service__pb2.CsvRequest.SerializeToString,
                response_deserializer=task__service__pb2.CsvResponse.FromString,
                _registered_method=True)
        self.CheckDomain = channel.unary_unary(
                '/taskservice.TaskService/CheckDomain',
                request_serializer=task__service__pb2.EmailRequest.SerializeToString,
                response_deserializer=task__service__pb2.DomainResponse.FromString,
                _registered_method=True)
        self.LongestWord = channel.unary_unary(
                '/taskservice.TaskService/LongestWord',
                request_serializer=task__service__pb2.TextRequest.SerializeToString,
                response_deserializer=task__service__pb2.WordResponse.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteCsv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LongestWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteCsv': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteCsv,
                    request_deserializer=task__service__pb2.CsvRequest.FromString,
                    response_serializer=task__service__pb2.CsvResponse.SerializeToString,
            ),
            'CheckDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDomain,
                    request_deserializer=task__service__pb2.EmailRequest.FromString,
                    response_serializer=task__service__pb2.DomainResponse.SerializeToString,
            ),
            'LongestWord': grpc.unary_unary_rpc_method_handler(
                    servicer.LongestWord,
                    request_deserializer=task__service__pb2.TextRequest.FromString,
                    response_serializer=task__service__pb2.WordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskservice.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskservice.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteCsv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskservice.TaskService/WriteCsv',
            task__service__pb2.CsvRequest.SerializeToString,
            task__service__pb2.CsvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskservice.TaskService/CheckDomain',
            task__service__pb2.EmailRequest.SerializeToString,
            task__service__pb2.DomainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LongestWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskservice.TaskService/LongestWord',
            task__service__pb2.TextRequest.SerializeToString,
            task__service__pb2.WordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
